# Generated by Django 3.2.25 on 2025-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='meetup.Participant'),
        ),
    ]
