# Generated by Django 3.2.25 on 2025-02-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_auto_20250214_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
    ]
