# Generated by Django 3.2.25 on 2025-02-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_remove_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='exe@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
