# Generated by Django 3.2.25 on 2025-02-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_meetup_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
    ]
