# Generated by Django 3.2.25 on 2025-02-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_auto_20250214_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2025-02-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
